### ISSUE TITLE
v1.4.10 esp_mqtt_client_subscribe errors with idf 5.2.1

### ISSUE THREAD

**Issue by JonathanWitthoeft** [espressif/esp-rainmaker-common#8]
### Checklist

- [x] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [x] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [x] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

Build with idf 5.2.1 as 1.4.9 did

### Actual behavior (suspected bug)

Has compilation errors regarding esp_mqtt_client_subscribe

### Error logs or terminal output

```shell
esp-idf/components/mqtt/esp-mqtt/include/mqtt_client.h:464:84: error: '_Generic' selector of type 'const char *' is not compatible with any association
  464 | #define esp_mqtt_client_subscribe(client_handle, topic_type, qos_or_size) _Generic((topic_type), \
      |                                                                                    ^
firmware/managed_components/espressif__rmaker_common/src/esp-mqtt/esp-mqtt-glue.c:162:23: note: in expansion of macro 'esp_mqtt_client_subscribe'
  162 |             int ret = esp_mqtt_client_subscribe(mqtt_data->mqtt_client, topic, qos);
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~
esp-idf/components/mqtt/esp-mqtt/include/mqtt_client.h:464:84: error: '_Generic' selector of type 'const char *' is not compatible with any association
  464 | #define esp_mqtt_client_subscribe(client_handle, topic_type, qos_or_size) _Generic((topic_type), \
      |                                                                                    ^
firmware/managed_components/espressif__rmaker_common/src/esp-mqtt/esp-mqtt-glue.c:206:19: note: in expansion of macro 'esp_mqtt_client_subscribe'
  206 |         int ret = esp_mqtt_client_subscribe(mqtt_data->mqtt_client, topic, qos);
```

### Steps to reproduce the behavior

Build with v1.4.9 and see no errors
Build with v1.4.10 and see errors

### Project release version

1.4.10

### System architecture

Intel/AMD 64-bit (modern PC, older Mac)

### Operating system

Linux

### Operating system version

Ubuntu

### Shell

CMD

**Comment by aceisace** [comment]
Same Error. My code stopped compiling suddenly with v1.4.10, v1.4.9 was working fine. Error:
```
mqtt_client.h:464:84: error: '_Generic' selector of type 'const char *' is not compatible with any association
  464 | #define esp_mqtt_client_subscribe(client_handle, topic_type, qos_or_size) _Generic((topic_type), \

esp-mqtt/esp-mqtt-glue.c:162:23: note: in expansion of macro 'esp_mqtt_client_subscribe'
  162 |             int ret = esp_mqtt_client_subscribe(mqtt_data->mqtt_client, topic, qos);

mqtt_client.h:464:84: error: '_Generic' selector of type 'const char *' is not compatible with any association
  464 | #define esp_mqtt_client_subscribe(client_handle, topic_type, qos_or_size) _Generic((topic_type), \

esp-mqtt-glue.c:206:19: note: in expansion of macro 'esp_mqtt_client_subscribe'
  206 |         int ret = esp_mqtt_client_subscribe(mqtt_data->mqtt_client, topic, qos);
```

@shahpiyushv I think this is related to the last PR. Please undo these changes - it will cause a lot of frustration for many in a very short time

**Comment by SCCatADT** [comment]
Having the same issue. 
I managed to resolve this by creating a similar work around as suggested [here](https://github.com/espressif/esp-mqtt/commit/32102558d3c0d58c8ed45e0029a29da26cb398a5#r139737900) but it may not be a clean solution and best to set dependency version range to "<1.4.9" for now.
